### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by PawanKolhe** [Qrivi/RLRSS#1]
Seems like the RSS feed is no longer pulling data.

**Comment by Qrivi** [comment]
Thanks for letting me know! The url from which the news is fetched seems to have changed. Unfortunately it no longer lists all the news at once now (need to set request param `p` to define which batch of 12 articles to fetch, e.g. https://www.rocketleague.com/ajax/articles-infinite/?p=2), so I'll need a bit longer to get this working again.

In the meantime, you might consider the Steam Feed for Rocket League: https://steamcommunity.com/games/252950/rss/. It’s basically the same feed, but with a delay (last article is not on there yet though it was published 5 days ago) plus some Steam exclusive updates.

**Comment by Qrivi** [comment]
Should be fixed in PR #2!  Let me know if something still isn't right. :)
