### ISSUE TITLE
Not working after Rocket League website update

### ISSUE THREAD

**Issue by Qrivi** [Qrivi/RLRSS#6]
The news section on the Rocket League website was updated anticipating the F2P update. The redesign seems to have broken the scraper.

**Comment by Miniontoby** [comment]
Check my PR: https://github.com/Qrivi/RLRSS/pull/7

**Comment by Qrivi** [comment]
Thanks a lot for your PR, @Miniontoby! ngl I had already forgotten about this, but it's awesome that you took the time to update the script. 😊

**Comment by Miniontoby** [comment]
You need to update the README.md file with the updated information

it still says its not fixed
